[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_bet = "79Td1aPg8V5PUQKDHZGLDDcp66Kuhq7tqsQdheXRmBXd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/prawin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
